DROP TABLE MANTENIMIENTO;
SET SERVEROUTPUT ON;
SET LINE WINDOW;
CREATE OR REPLACE PROCEDURE spConsulta(vPaciente IN NUMBER
,vTrat IN VARCHAR,vConsultorio IN NUMBER,vFin IN CHAR)
AS
    vSuc VARCHAR(18);
    vOdo NUMBER(20);
    vConsulta NUMBER(30);
BEGIN
    SELECT MAX(NUMCONSULTA) INTO vConsulta
    FROM HISTCLINICA
    WHERE CEDULAIDE=vPaciente;
    SELECT NOMBRESUC,CEDULAODO INTO vSuc,vOdo
    FROM AFILIADO
    WHERE CEDULAIDE=vPaciente;
    IF (vConsulta IS NULL) THEN
        vConsulta := 1;
    ELSE
        vConsulta := vConsulta+1;
    END IF;
    INSERT INTO HISTCLINICA (CEDULAIDE,NUMCONSULTA,NOMBRESUC,
    CEDULAODO,NUMCONS,ABVNOM,FINALIZACION)
    VALUES(vPaciente,vConsulta,vSuc,vOdo,vConsultorio,vTrat,vFin);
end spConsulta;
/
EXEC spConsulta(7234567890,'CIR',15,'N');
SELECT * FROM HistClinica;
ROLLBACK;

CREATE OR REPLACE VIEW vwMesAfCos
AS
SELECT CEDULAIDE,NOMAF||' '||APPATAF||' '||APMATAF AS AFILIADO,
TO_CHAR(FECHACONS,'MONTH/YY') AS MES,SUM(COSTO) AS TOTAL_PAGOS FROM
HISTCLINICA JOIN TRATAMIENTO USING(ABVNOM) JOIN AFILIADO USING(CEDULAIDE)
GROUP BY CEDULAIDE,NOMAF||' '||APPATAF||' '||APMATAF,TO_CHAR(FECHACONS,'MONTH/YY');

SELECT * FROM vwMesAfCos;

CREATE OR REPLACE VIEW vwConvenioRebaja
AS
SELECT NOMBRECONV AS CONVENIO,PORCREB AS REBAJA
FROM GRUPAL;

SELECT * FROM vwConvenioRebaja;

CREATE OR REPLACE VIEW vwSucTrat
AS
SELECT NOMBRESUC AS SUCURSAL,CIUDADSUC||', '||CALLESUC||' #'||NUMEROSUC AS DIRECCION
,ABVNOM AS TRATAMIENTO
FROM SUCURSAL JOIN SUCODO USING(NOMBRESUC)
JOIN ODONTOLOGO USING(CEDULAODO)
JOIN REALIZA USING(CEDULAODO);

SELECT * FROM vwSucTrat;

CREATE OR REPLACE FUNCTION ftDescuento(vAf IN NUMBER,vMes IN DATE)
RETURN NUMBER
IS
    vPago NUMBER(6);
    vReb NUMBER(4,2);
BEGIN
    SELECT TOTAL_PAGOS,PORCREB INTO vPago,vReb FROM
    GRUPAL JOIN vwMesAfCos USING(CEDULAIDE)
    WHERE MES = TO_CHAR(vMes,'MONTH/YY') AND CEDULAIDE=vAf;
    vPago:=vPago*(1-vReb/100);
    RETURN(vPago);
END ftDescuento;
/

SELECT TOTAL_PAGOS,PORCREB AS REBAJA,ftDescuento(7234509876,'1/07/12') AS PAGO_FINAL
FROM GRUPAL JOIN vwMesAfCos USING(CEDULAIDE)
WHERE CEDULAIDE=7234509876;

CREATE OR REPLACE VIEW vwHorariosOdo
AS
SELECT NOMBRESUC AS SUCURSAL,NOMOD||' '||APPATOD||' '||APMATOD AS ODONTOLOGO,HORARIOATE AS HORARIO
FROM SUCODO JOIN ODONTOLOGO USING(CEDULAODO)
ORDER BY SUCURSAL;

SELECT * FROM vwHorariosOdo;

CREATE OR REPLACE VIEW vwTrataAf
AS
SELECT A.NOMBRESUC AS SUCURSAL,NOMAF||' '||APPATAF||' '||APMATAF AS AFILIADO,ABVNOM AS TRATAMIENTO
FROM HISTCLINICA JOIN AFILIADO A USING(CEDULAIDE)
ORDER BY SUCURSAL;

SELECT * FROM vwTrataAf;

CREATE TABLE MANTENIMIENTO(
nombreSuc VARCHAR2(18),
numCons NUMBER(4),
TipoEq VARCHAR2(18),
FechaMant DATE
);

CREATE OR REPLACE TRIGGER tgMantenimiento
AFTER INSERT OR UPDATE OF FechaMant
ON EQUIPAMIENTO
FOR EACH ROW
BEGIN
	INSERT INTO MANTENIMIENTO (nombreSuc,numCons,TipoEq,FechaMant)
	VALUES (:NEW.nombreSuc,:NEW.numCons,:NEW.TipoEq,:NEW.FechaMant);
END tgMantenimiento;
/

UPDATE EQUIPAMIENTO SET FechaMant=SYSDATE WHERE NumSerie=1111111111;

SELECT * FROM MANTENIMIENTO;
ROLLBACK;

CREATE OR REPLACE VIEW vwDatosOdontologo
AS
SELECT CEDULAODO AS CEDULA,NOMOD||' '||APPATOD||' '||APMATOD AS ODONTOLOGO,
ESPECIALIDAD,ABVNOM AS TRATAMIENTO,NOMBRESUC AS SUCURSAL
FROM SUCODO JOIN ODONTOLOGO USING(CEDULAODO)
JOIN REALIZA USING(CEDULAODO)
ORDER BY CEDULAODO;

SELECT * FROM vwDatosOdontologo;

CREATE OR REPLACE VIEW vwMontoSucTrat
AS
SELECT NOMBRESUC AS SUCURSAL,TO_CHAR(FECHACONS,'MONTH/YY') AS MES,SUM(COSTO) AS TOTAL_PAGOS FROM
HISTCLINICA JOIN TRATAMIENTO USING(ABVNOM)
GROUP BY NOMBRESUC,TO_CHAR(FECHACONS,'MONTH/YY')
ORDER BY NOMBRESUC;

SELECT * FROM vwMontoSucTrat;